# ==========================================================
# COST OPTIMIZATION AGENT — RATE CONFIGURATION
# Milestone 4: Cost Optimization & Enterprise Deployment
#
# None of the underlying datasets (energy, maintenance, occupancy,
# security) contain real cost figures, so this file holds the
# assumed cost rates the Cost Optimization Agent applies on top of
# existing usage/event data. Tune these to match real facility
# billing/contract figures if you have them — nothing else in the
# codebase needs to change.
# ==========================================================

# ---- ENERGY -------------------------------------------------
# ₹ per kWh, typical Indian commercial/industrial tariff
RATE_PER_KWH = 8.5

# Potential % reduction in energy cost if HVAC/lighting/renewable
# recommendations (already generated by the Energy Agent) are followed
ENERGY_OPTIMIZATION_SAVINGS_PCT = 0.15

# ---- MAINTENANCE ---------------------------------------------
# ₹ cost of an actual failure/breakdown event (repair + downtime)
MAINTENANCE_COST_PER_FAILURE = 25000

# ₹ cost of a preventive inspection for a device in Critical health band
MAINTENANCE_COST_PER_CRITICAL_INSPECTION = 6000

# ₹ cost of a preventive inspection for a device in Warning health band
MAINTENANCE_COST_PER_WARNING_INSPECTION = 2000

# Potential % reduction in maintenance cost from predictive vs. reactive
# maintenance (catching Warning/Critical devices before they fail)
MAINTENANCE_OPTIMIZATION_SAVINGS_PCT = 0.30

# ---- SECURITY --------------------------------------------------
# ₹ cost per security event, by severity (response, investigation, etc.)
SECURITY_COST_PER_CRITICAL_EVENT = 15000
SECURITY_COST_PER_HIGH_EVENT = 7000
SECURITY_COST_PER_MEDIUM_EVENT = 2000
SECURITY_COST_PER_LOW_EVENT = 500

# ₹ cost per denied access attempt (guard/admin follow-up)
SECURITY_COST_PER_DENIED_ACCESS = 150

# ₹ cost per visitor visit (badge issuance, escort/monitoring overhead)
SECURITY_COST_PER_VISITOR = 300

# Potential % reduction in security cost via proactive monitoring
# (fewer escalations, faster resolution)
SECURITY_OPTIMIZATION_SAVINGS_PCT = 0.20

# Reporting period (days) the cost dashboard represents — used to turn
# the per-day admin rate into a period total alongside the other
# categories, which are derived from however much data is on hand.
REPORTING_PERIOD_DAYS = 30

# ---- ADMINISTRATIVE ---------------------------------------------
# ₹ flat overhead per zone per day (facilities admin, utilities admin,
# building management) — the one cost category with no source dataset
ADMIN_COST_PER_ZONE_PER_DAY = 400

# Potential % reduction in admin overhead via cross-agent automation
ADMIN_OPTIMIZATION_SAVINGS_PCT = 0.10

# ---- FACILITY HEALTH SCORE WEIGHTS -------------------------------
# Must sum to 1.0. Combines all four agents into one composite score.
HEALTH_WEIGHT_MAINTENANCE = 0.35
HEALTH_WEIGHT_ENERGY = 0.25
HEALTH_WEIGHT_SECURITY = 0.25
HEALTH_WEIGHT_OCCUPANCY = 0.15

# "Ideal" average occupancy % — used to score occupancy health.
# Too low wastes space, too high risks overcrowding.
OCCUPANCY_HEALTH_TARGET_PCT = 65

# Severity weights used to normalize the Security component of the
# Facility Health score (0-100) regardless of total event volume.
SECURITY_SEVERITY_WEIGHTS = {
    "CRITICAL": 4,
    "HIGH": 2,
    "MEDIUM": 1,
    "LOW": 0.2
}

# ---- BUDGET & ORCHESTRATION -------------------------------------
# ₹ approved monthly operating budget target, used to compute variance
# against the actual cost the Cost Optimization Agent derives from
# live usage data. Tune to match a real approved facility budget.
BASELINE_MONTHLY_BUDGET = 175000

# Below this ₹ savings threshold, an optimization is considered
# low-risk enough for the orchestrator to auto-execute; above it,
# the action is only detected and flagged for manual approval.
ORCHESTRATION_AUTO_EXECUTE_THRESHOLD = 5000

# Which agents are "involved" in an orchestration action, by category —
# purely descriptive, shown in the Cross-Agent Orchestration Center.
ORCHESTRATION_AGENTS_BY_CATEGORY = {
    "Maintenance": ["Maintenance Agent", "Cost Agent"],
    "Energy": ["Energy Agent", "Occupancy Agent", "Cost Agent"],
    "Security": ["Security Agent", "Cost Agent"],
    "Administrative": ["Cost Agent"]
}